from django.contrib import admin

from aproap.models import *

admin.site.register(ideaDeQuestao)
admin.site.register(Projeto)
admin.site.register(votosQuestao)
admin.site.register(espacoProjeto)
admin.site.register(alunosNoProjeto)
admin.site.register(conhecimento)
admin.site.register(resultadoVotacao)
admin.site.register(unidadeInvestigacao)
admin.site.register(tarefasItem)
admin.site.register(elementoTextual)
admin.site.register(textoProduzido)
admin.site.register(ajudantes)
admin.site.register(conversa)
admin.site.register(mensagemAssistente)
admin.site.register(mapaConceitual)
admin.site.register(postagem)
admin.site.register(respostas)
admin.site.register(mensagemDeContato)
admin.site.register(historicoAluno)
admin.site.register(Usuarios)
admin.site.register(atividadesCampo)